// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MatchmakingMessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Axlebolt.Bolt.Protobuf {

  /// <summary>Holder for reflection information generated from MatchmakingMessage.proto</summary>
  public static partial class MatchmakingMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for MatchmakingMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MatchmakingMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhNYXRjaG1ha2luZ01lc3NhZ2UucHJvdG8SF0F4bGVib2x0LkJvbHQuUHJv",
            "dG9idWYyGhNDb21tb25NZXNzYWdlLnByb3RvGhRGcmllbmRzTWVzc2FnZS5w",
            "cm90byKBAgoRR2FtZVNlcnZlckRldGFpbHMSCgoCaWQYASABKAkSNwoKZ2Ft",
            "ZVNlcnZlchgCIAEoCzIjLkF4bGVib2x0LkJvbHQuUHJvdG9idWYyLkdhbWVT",
            "ZXJ2ZXISCwoDbWFwGAMgASgJEhYKDmN1cnJlbnRQbGF5ZXJzGAQgASgFEhIK",
            "Cm1heFBsYXllcnMYBSABKAUSEgoKYm90UGxheWVycxgGIAEoBRIXCg9yZXF1",
            "aXJlUGFzc3dvcmQYByABKAgSDwoHdmVyc2lvbhgIIAEoCRIaChJzdWNjZXNz",
            "ZnVsUmVzcG9uc2UYCSABKAgSFAoMZG9Ob3RSZWZyZXNoGAogASgIIu8ECgVM",
            "b2JieRIKCgJpZBgBIAEoCRIVCg1vd25lclBsYXllcklkGAIgASgJEgwKBG5h",
            "bWUYAyABKAkSNQoJbG9iYnlUeXBlGAQgASgOMiIuQXhsZWJvbHQuQm9sdC5Q",
            "cm90b2J1ZjIuTG9iYnlUeXBlEhAKCGpvaW5hYmxlGAUgASgIEhIKCm1heE1l",
            "bWJlcnMYBiABKAUSNgoEZGF0YRgHIAMoCzIoLkF4bGVib2x0LkJvbHQuUHJv",
            "dG9idWYyLkxvYmJ5LkRhdGFFbnRyeRI2CgdtZW1iZXJzGAggAygLMiUuQXhs",
            "ZWJvbHQuQm9sdC5Qcm90b2J1ZjIuUGxheWVyRnJpZW5kEjYKB2ludml0ZXMY",
            "CSADKAsyJS5BeGxlYm9sdC5Cb2x0LlByb3RvYnVmMi5QbGF5ZXJGcmllbmQS",
            "NwoKZ2FtZVNlcnZlchgKIAEoCzIjLkF4bGVib2x0LkJvbHQuUHJvdG9idWYy",
            "LkdhbWVTZXJ2ZXISNwoKcGhvdG9uR2FtZRgLIAEoCzIjLkF4bGVib2x0LkJv",
            "bHQuUHJvdG9idWYyLlBob3RvbkdhbWUSFQoNbWF4U3BlY3RhdG9ycxgMIAEo",
            "BRI5CgpzcGVjdGF0b3JzGA0gAygLMiUuQXhsZWJvbHQuQm9sdC5Qcm90b2J1",
            "ZjIuUGxheWVyRnJpZW5kEj8KEHNwZWN0YXRvckludml0ZXMYDiADKAsyJS5B",
            "eGxlYm9sdC5Cb2x0LlByb3RvYnVmMi5QbGF5ZXJGcmllbmQaKwoJRGF0YUVu",
            "dHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiqAEKC0xvYmJ5",
            "SW52aXRlEg8KB2xvYmJ5SWQYASABKAkSPAoNaW52aXRlQ3JlYXRvchgCIAEo",
            "CzIlLkF4bGVib2x0LkJvbHQuUHJvdG9idWYyLlBsYXllckZyaWVuZBIMCgRk",
            "YXRlGAMgASgDEjwKCnBsYXllclR5cGUYBCABKA4yKC5BeGxlYm9sdC5Cb2x0",
            "LlByb3RvYnVmMi5Mb2JieVBsYXllclR5cGUiIwoQSm9pbkxvYmJ5UmVxdWVz",
            "dBIPCgdsb2JieUlkGAEgASgJImMKEkpvaW5Mb2JieUFzUmVxdWVzdBIPCgds",
            "b2JieUlkGAEgASgJEjwKCnBsYXllclR5cGUYAiABKA4yKC5BeGxlYm9sdC5C",
            "b2x0LlByb3RvYnVmMi5Mb2JieVBsYXllclR5cGUiNQoaSW52aXRlUGxheWVy",
            "VG9Mb2JieVJlcXVlc3QSFwoPaW52aXRlZFBsYXllcklkGAEgASgJInUKHElu",
            "dml0ZVBsYXllclRvTG9iYnlBc1JlcXVlc3QSFwoPaW52aXRlZFBsYXllcklk",
            "GAEgASgJEjwKCnBsYXllclR5cGUYAiABKA4yKC5BeGxlYm9sdC5Cb2x0LlBy",
            "b3RvYnVmMi5Mb2JieVBsYXllclR5cGUiPwokUmV2b2tlUGxheWVySW52aXRh",
            "dGlvblRvTG9iYnlSZXF1ZXN0EhcKD3Jldm9rZWRQbGF5ZXJJZBgBIAEoCSIx",
            "Ch5SZWZ1c2VJbnZpdGF0aW9uVG9Mb2JieVJlcXVlc3QSDwoHbG9iYnlJZBgB",
            "IAEoCSI0ChpLaWNrUGxheWVyRnJvbUxvYmJ5UmVxdWVzdBIWCg5raWNrZWRQ",
            "bGF5ZXJJZBgBIAEoCSIaChhHZXRJbnZpdGVzVG9Mb2JieVJlcXVlc3QiVwoZ",
            "R2V0SW52aXRlc1RvTG9iYnlSZXNwb25zZRI6Cgxsb2JieUludml0ZXMYASAD",
            "KAsyJC5BeGxlYm9sdC5Cb2x0LlByb3RvYnVmMi5Mb2JieUludml0ZSpFCglM",
            "b2JieVR5cGUSCwoHUFJJVkFURRAAEhAKDEZSSUVORFNfT05MWRABEgoKBlBV",
            "QkxJQxACEg0KCUlOVklTSUJMRRADKjUKD0xvYmJ5UGxheWVyVHlwZRIHCgNB",
            "TlkQABIKCgZNRU1CRVIQARINCglTUEVDVEFUT1IQAipFChNMb2JieURpc3Rh",
            "bmNlRmlsdGVyEgkKBUNMT1NFEAASCwoHREVGQVVMVBABEgcKA0ZBUhACEg0K",
            "CVdPUkxEV0lERRADQhmqAhZBeGxlYm9sdC5Cb2x0LlByb3RvYnVmYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Axlebolt.Bolt.Protobuf.CommonMessageReflection.Descriptor, global::Axlebolt.Bolt.Protobuf.FriendsMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Axlebolt.Bolt.Protobuf.LobbyType), typeof(global::Axlebolt.Bolt.Protobuf.LobbyPlayerType), typeof(global::Axlebolt.Bolt.Protobuf.LobbyDistanceFilter), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.GameServerDetails), global::Axlebolt.Bolt.Protobuf.GameServerDetails.Parser, new[]{ "Id", "GameServer", "Map", "CurrentPlayers", "MaxPlayers", "BotPlayers", "RequirePassword", "Version", "SuccessfulResponse", "DoNotRefresh" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.Lobby), global::Axlebolt.Bolt.Protobuf.Lobby.Parser, new[]{ "Id", "OwnerPlayerId", "Name", "LobbyType", "Joinable", "MaxMembers", "Data", "Members", "Invites", "GameServer", "PhotonGame", "MaxSpectators", "Spectators", "SpectatorInvites" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.LobbyInvite), global::Axlebolt.Bolt.Protobuf.LobbyInvite.Parser, new[]{ "LobbyId", "InviteCreator", "Date", "PlayerType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.JoinLobbyRequest), global::Axlebolt.Bolt.Protobuf.JoinLobbyRequest.Parser, new[]{ "LobbyId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.JoinLobbyAsRequest), global::Axlebolt.Bolt.Protobuf.JoinLobbyAsRequest.Parser, new[]{ "LobbyId", "PlayerType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.InvitePlayerToLobbyRequest), global::Axlebolt.Bolt.Protobuf.InvitePlayerToLobbyRequest.Parser, new[]{ "InvitedPlayerId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.InvitePlayerToLobbyAsRequest), global::Axlebolt.Bolt.Protobuf.InvitePlayerToLobbyAsRequest.Parser, new[]{ "InvitedPlayerId", "PlayerType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.RevokePlayerInvitationToLobbyRequest), global::Axlebolt.Bolt.Protobuf.RevokePlayerInvitationToLobbyRequest.Parser, new[]{ "RevokedPlayerId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.RefuseInvitationToLobbyRequest), global::Axlebolt.Bolt.Protobuf.RefuseInvitationToLobbyRequest.Parser, new[]{ "LobbyId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.KickPlayerFromLobbyRequest), global::Axlebolt.Bolt.Protobuf.KickPlayerFromLobbyRequest.Parser, new[]{ "KickedPlayerId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.GetInvitesToLobbyRequest), global::Axlebolt.Bolt.Protobuf.GetInvitesToLobbyRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Axlebolt.Bolt.Protobuf.GetInvitesToLobbyResponse), global::Axlebolt.Bolt.Protobuf.GetInvitesToLobbyResponse.Parser, new[]{ "LobbyInvites" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum LobbyType {
    [pbr::OriginalName("PRIVATE")] Private = 0,
    [pbr::OriginalName("FRIENDS_ONLY")] FriendsOnly = 1,
    [pbr::OriginalName("PUBLIC")] Public = 2,
    [pbr::OriginalName("INVISIBLE")] Invisible = 3,
  }

  public enum LobbyPlayerType {
    [pbr::OriginalName("ANY")] Any = 0,
    [pbr::OriginalName("MEMBER")] Member = 1,
    [pbr::OriginalName("SPECTATOR")] Spectator = 2,
  }

  public enum LobbyDistanceFilter {
    [pbr::OriginalName("CLOSE")] Close = 0,
    [pbr::OriginalName("DEFAULT")] Default = 1,
    [pbr::OriginalName("FAR")] Far = 2,
    [pbr::OriginalName("WORLDWIDE")] Worldwide = 3,
  }

  #endregion

  #region Messages
  public sealed partial class GameServerDetails : pb::IMessage<GameServerDetails> {
    private static readonly pb::MessageParser<GameServerDetails> _parser = new pb::MessageParser<GameServerDetails>(() => new GameServerDetails());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameServerDetails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameServerDetails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameServerDetails(GameServerDetails other) : this() {
      id_ = other.id_;
      GameServer = other.gameServer_ != null ? other.GameServer.Clone() : null;
      map_ = other.map_;
      currentPlayers_ = other.currentPlayers_;
      maxPlayers_ = other.maxPlayers_;
      botPlayers_ = other.botPlayers_;
      requirePassword_ = other.requirePassword_;
      version_ = other.version_;
      successfulResponse_ = other.successfulResponse_;
      doNotRefresh_ = other.doNotRefresh_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameServerDetails Clone() {
      return new GameServerDetails(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gameServer" field.</summary>
    public const int GameServerFieldNumber = 2;
    private global::Axlebolt.Bolt.Protobuf.GameServer gameServer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Axlebolt.Bolt.Protobuf.GameServer GameServer {
      get { return gameServer_; }
      set {
        gameServer_ = value;
      }
    }

    /// <summary>Field number for the "map" field.</summary>
    public const int MapFieldNumber = 3;
    private string map_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Map {
      get { return map_; }
      set {
        map_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "currentPlayers" field.</summary>
    public const int CurrentPlayersFieldNumber = 4;
    private int currentPlayers_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CurrentPlayers {
      get { return currentPlayers_; }
      set {
        currentPlayers_ = value;
      }
    }

    /// <summary>Field number for the "maxPlayers" field.</summary>
    public const int MaxPlayersFieldNumber = 5;
    private int maxPlayers_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxPlayers {
      get { return maxPlayers_; }
      set {
        maxPlayers_ = value;
      }
    }

    /// <summary>Field number for the "botPlayers" field.</summary>
    public const int BotPlayersFieldNumber = 6;
    private int botPlayers_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BotPlayers {
      get { return botPlayers_; }
      set {
        botPlayers_ = value;
      }
    }

    /// <summary>Field number for the "requirePassword" field.</summary>
    public const int RequirePasswordFieldNumber = 7;
    private bool requirePassword_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool RequirePassword {
      get { return requirePassword_; }
      set {
        requirePassword_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 8;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "successfulResponse" field.</summary>
    public const int SuccessfulResponseFieldNumber = 9;
    private bool successfulResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool SuccessfulResponse {
      get { return successfulResponse_; }
      set {
        successfulResponse_ = value;
      }
    }

    /// <summary>Field number for the "doNotRefresh" field.</summary>
    public const int DoNotRefreshFieldNumber = 10;
    private bool doNotRefresh_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool DoNotRefresh {
      get { return doNotRefresh_; }
      set {
        doNotRefresh_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameServerDetails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameServerDetails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(GameServer, other.GameServer)) return false;
      if (Map != other.Map) return false;
      if (CurrentPlayers != other.CurrentPlayers) return false;
      if (MaxPlayers != other.MaxPlayers) return false;
      if (BotPlayers != other.BotPlayers) return false;
      if (RequirePassword != other.RequirePassword) return false;
      if (Version != other.Version) return false;
      if (SuccessfulResponse != other.SuccessfulResponse) return false;
      if (DoNotRefresh != other.DoNotRefresh) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (gameServer_ != null) hash ^= GameServer.GetHashCode();
      if (Map.Length != 0) hash ^= Map.GetHashCode();
      if (CurrentPlayers != 0) hash ^= CurrentPlayers.GetHashCode();
      if (MaxPlayers != 0) hash ^= MaxPlayers.GetHashCode();
      if (BotPlayers != 0) hash ^= BotPlayers.GetHashCode();
      if (RequirePassword != false) hash ^= RequirePassword.GetHashCode();
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      if (SuccessfulResponse != false) hash ^= SuccessfulResponse.GetHashCode();
      if (DoNotRefresh != false) hash ^= DoNotRefresh.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (gameServer_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GameServer);
      }
      if (Map.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Map);
      }
      if (CurrentPlayers != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CurrentPlayers);
      }
      if (MaxPlayers != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxPlayers);
      }
      if (BotPlayers != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(BotPlayers);
      }
      if (RequirePassword != false) {
        output.WriteRawTag(56);
        output.WriteBool(RequirePassword);
      }
      if (Version.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Version);
      }
      if (SuccessfulResponse != false) {
        output.WriteRawTag(72);
        output.WriteBool(SuccessfulResponse);
      }
      if (DoNotRefresh != false) {
        output.WriteRawTag(80);
        output.WriteBool(DoNotRefresh);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (gameServer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameServer);
      }
      if (Map.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Map);
      }
      if (CurrentPlayers != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentPlayers);
      }
      if (MaxPlayers != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxPlayers);
      }
      if (BotPlayers != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BotPlayers);
      }
      if (RequirePassword != false) {
        size += 1 + 1;
      }
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (SuccessfulResponse != false) {
        size += 1 + 1;
      }
      if (DoNotRefresh != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameServerDetails other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.gameServer_ != null) {
        if (gameServer_ == null) {
          gameServer_ = new global::Axlebolt.Bolt.Protobuf.GameServer();
        }
        GameServer.MergeFrom(other.GameServer);
      }
      if (other.Map.Length != 0) {
        Map = other.Map;
      }
      if (other.CurrentPlayers != 0) {
        CurrentPlayers = other.CurrentPlayers;
      }
      if (other.MaxPlayers != 0) {
        MaxPlayers = other.MaxPlayers;
      }
      if (other.BotPlayers != 0) {
        BotPlayers = other.BotPlayers;
      }
      if (other.RequirePassword != false) {
        RequirePassword = other.RequirePassword;
      }
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      if (other.SuccessfulResponse != false) {
        SuccessfulResponse = other.SuccessfulResponse;
      }
      if (other.DoNotRefresh != false) {
        DoNotRefresh = other.DoNotRefresh;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (gameServer_ == null) {
              gameServer_ = new global::Axlebolt.Bolt.Protobuf.GameServer();
            }
            input.ReadMessage(gameServer_);
            break;
          }
          case 26: {
            Map = input.ReadString();
            break;
          }
          case 32: {
            CurrentPlayers = input.ReadInt32();
            break;
          }
          case 40: {
            MaxPlayers = input.ReadInt32();
            break;
          }
          case 48: {
            BotPlayers = input.ReadInt32();
            break;
          }
          case 56: {
            RequirePassword = input.ReadBool();
            break;
          }
          case 66: {
            Version = input.ReadString();
            break;
          }
          case 72: {
            SuccessfulResponse = input.ReadBool();
            break;
          }
          case 80: {
            DoNotRefresh = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Lobby : pb::IMessage<Lobby> {
    private static readonly pb::MessageParser<Lobby> _parser = new pb::MessageParser<Lobby>(() => new Lobby());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Lobby> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Lobby() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Lobby(Lobby other) : this() {
      id_ = other.id_;
      ownerPlayerId_ = other.ownerPlayerId_;
      name_ = other.name_;
      lobbyType_ = other.lobbyType_;
      joinable_ = other.joinable_;
      maxMembers_ = other.maxMembers_;
      data_ = other.data_.Clone();
      members_ = other.members_.Clone();
      invites_ = other.invites_.Clone();
      GameServer = other.gameServer_ != null ? other.GameServer.Clone() : null;
      PhotonGame = other.photonGame_ != null ? other.PhotonGame.Clone() : null;
      maxSpectators_ = other.maxSpectators_;
      spectators_ = other.spectators_.Clone();
      spectatorInvites_ = other.spectatorInvites_.Clone();
      numberOfMembers_ = other.numberOfMembers_;
      numberOfSpectators_ = other.numberOfSpectators_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Lobby Clone() {
      return new Lobby(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ownerPlayerId" field.</summary>
    public const int OwnerPlayerIdFieldNumber = 2;
    private string ownerPlayerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OwnerPlayerId {
      get { return ownerPlayerId_; }
      set {
        ownerPlayerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lobbyType" field.</summary>
    public const int LobbyTypeFieldNumber = 4;
    private global::Axlebolt.Bolt.Protobuf.LobbyType lobbyType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Axlebolt.Bolt.Protobuf.LobbyType LobbyType {
      get { return lobbyType_; }
      set {
        lobbyType_ = value;
      }
    }

    /// <summary>Field number for the "joinable" field.</summary>
    public const int JoinableFieldNumber = 5;
    private bool joinable_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Joinable {
      get { return joinable_; }
      set {
        joinable_ = value;
      }
    }

    /// <summary>Field number for the "maxMembers" field.</summary>
    public const int MaxMembersFieldNumber = 6;
    private int maxMembers_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxMembers {
      get { return maxMembers_; }
      set {
        maxMembers_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 7;
    private static readonly pbc::MapField<string, string>.Codec _map_data_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 58);
    private readonly pbc::MapField<string, string> data_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Data {
      get { return data_; }
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Axlebolt.Bolt.Protobuf.PlayerFriend> _repeated_members_codec
        = pb::FieldCodec.ForMessage(66, global::Axlebolt.Bolt.Protobuf.PlayerFriend.Parser);
    private readonly pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend> members_ = new pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend> Members {
      get { return members_; }
    }

    /// <summary>Field number for the "invites" field.</summary>
    public const int InvitesFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Axlebolt.Bolt.Protobuf.PlayerFriend> _repeated_invites_codec
        = pb::FieldCodec.ForMessage(74, global::Axlebolt.Bolt.Protobuf.PlayerFriend.Parser);
    private readonly pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend> invites_ = new pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend> Invites {
      get { return invites_; }
    }

    /// <summary>Field number for the "gameServer" field.</summary>
    public const int GameServerFieldNumber = 10;
    private global::Axlebolt.Bolt.Protobuf.GameServer gameServer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Axlebolt.Bolt.Protobuf.GameServer GameServer {
      get { return gameServer_; }
      set {
        gameServer_ = value;
      }
    }

    /// <summary>Field number for the "photonGame" field.</summary>
    public const int PhotonGameFieldNumber = 11;
    private global::Axlebolt.Bolt.Protobuf.PhotonGame photonGame_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Axlebolt.Bolt.Protobuf.PhotonGame PhotonGame {
      get { return photonGame_; }
      set {
        photonGame_ = value;
      }
    }

    /// <summary>Field number for the "maxSpectators" field.</summary>
    public const int MaxSpectatorsFieldNumber = 12;
    private int maxSpectators_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxSpectators {
      get { return maxSpectators_; }
      set {
        maxSpectators_ = value;
      }
    }

    /// <summary>Field number for the "spectators" field.</summary>
    public const int SpectatorsFieldNumber = 13;
    private static readonly pb::FieldCodec<global::Axlebolt.Bolt.Protobuf.PlayerFriend> _repeated_spectators_codec
        = pb::FieldCodec.ForMessage(106, global::Axlebolt.Bolt.Protobuf.PlayerFriend.Parser);
    private readonly pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend> spectators_ = new pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend> Spectators {
      get { return spectators_; }
    }

    /// <summary>Field number for the "spectatorInvites" field.</summary>
    public const int SpectatorInvitesFieldNumber = 14;
    private static readonly pb::FieldCodec<global::Axlebolt.Bolt.Protobuf.PlayerFriend> _repeated_spectatorInvites_codec
        = pb::FieldCodec.ForMessage(114, global::Axlebolt.Bolt.Protobuf.PlayerFriend.Parser);
    private readonly pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend> spectatorInvites_ = new pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.PlayerFriend> SpectatorInvites {
      get { return spectatorInvites_; }
    }

    /// <summary>Field number for the "numberOfMembers" field.</summary>
    public const int NumberOfMembersFieldNumber = 15;
    private int numberOfMembers_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NumberOfMembers {
      get { return numberOfMembers_; }
      set {
        numberOfMembers_ = value;
      }
    }

    /// <summary>Field number for the "numberOfSpectators" field.</summary>
    public const int NumberOfSpectatorsFieldNumber = 16;
    private int numberOfSpectators_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NumberOfSpectators {
      get { return numberOfSpectators_; }
      set {
        numberOfSpectators_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Lobby);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Lobby other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (OwnerPlayerId != other.OwnerPlayerId) return false;
      if (Name != other.Name) return false;
      if (LobbyType != other.LobbyType) return false;
      if (Joinable != other.Joinable) return false;
      if (MaxMembers != other.MaxMembers) return false;
      if (!Data.Equals(other.Data)) return false;
      if(!members_.Equals(other.members_)) return false;
      if(!invites_.Equals(other.invites_)) return false;
      if (!object.Equals(GameServer, other.GameServer)) return false;
      if (!object.Equals(PhotonGame, other.PhotonGame)) return false;
      if (MaxSpectators != other.MaxSpectators) return false;
      if(!spectators_.Equals(other.spectators_)) return false;
      if(!spectatorInvites_.Equals(other.spectatorInvites_)) return false;
      if (NumberOfMembers != other.NumberOfMembers) return false;
      if (NumberOfSpectators != other.NumberOfSpectators) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (OwnerPlayerId.Length != 0) hash ^= OwnerPlayerId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (LobbyType != 0) hash ^= LobbyType.GetHashCode();
      if (Joinable != false) hash ^= Joinable.GetHashCode();
      if (MaxMembers != 0) hash ^= MaxMembers.GetHashCode();
      hash ^= Data.GetHashCode();
      hash ^= members_.GetHashCode();
      hash ^= invites_.GetHashCode();
      if (gameServer_ != null) hash ^= GameServer.GetHashCode();
      if (photonGame_ != null) hash ^= PhotonGame.GetHashCode();
      if (MaxSpectators != 0) hash ^= MaxSpectators.GetHashCode();
      hash ^= spectators_.GetHashCode();
      hash ^= spectatorInvites_.GetHashCode();
      if (NumberOfMembers != 0) hash ^= NumberOfMembers.GetHashCode();
      if (NumberOfSpectators != 0) hash ^= NumberOfSpectators.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (OwnerPlayerId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OwnerPlayerId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (LobbyType != 0) {
        output.WriteRawTag(32);
        output.WriteEnum((int) LobbyType);
      }
      if (Joinable != false) {
        output.WriteRawTag(40);
        output.WriteBool(Joinable);
      }
      if (MaxMembers != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MaxMembers);
      }
      data_.WriteTo(output, _map_data_codec);
      members_.WriteTo(output, _repeated_members_codec);
      invites_.WriteTo(output, _repeated_invites_codec);
      if (gameServer_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(GameServer);
      }
      if (photonGame_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(PhotonGame);
      }
      if (MaxSpectators != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(MaxSpectators);
      }
      spectators_.WriteTo(output, _repeated_spectators_codec);
      spectatorInvites_.WriteTo(output, _repeated_spectatorInvites_codec);
      if (NumberOfMembers != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(NumberOfMembers);
      }
      if (NumberOfSpectators != 0) {
        output.WriteRawTag(128);
        output.WriteInt32(NumberOfSpectators);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (OwnerPlayerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OwnerPlayerId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (LobbyType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LobbyType);
      }
      if (Joinable != false) {
        size += 1 + 1;
      }
      if (MaxMembers != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxMembers);
      }
      size += data_.CalculateSize(_map_data_codec);
      size += members_.CalculateSize(_repeated_members_codec);
      size += invites_.CalculateSize(_repeated_invites_codec);
      if (gameServer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameServer);
      }
      if (photonGame_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PhotonGame);
      }
      if (MaxSpectators != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxSpectators);
      }
      size += spectators_.CalculateSize(_repeated_spectators_codec);
      size += spectatorInvites_.CalculateSize(_repeated_spectatorInvites_codec);
      if (NumberOfMembers != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfMembers);
      }
      if (NumberOfSpectators != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfSpectators);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Lobby other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.OwnerPlayerId.Length != 0) {
        OwnerPlayerId = other.OwnerPlayerId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.LobbyType != 0) {
        LobbyType = other.LobbyType;
      }
      if (other.Joinable != false) {
        Joinable = other.Joinable;
      }
      if (other.MaxMembers != 0) {
        MaxMembers = other.MaxMembers;
      }
      data_.Add(other.data_);
      members_.Add(other.members_);
      invites_.Add(other.invites_);
      if (other.gameServer_ != null) {
        if (gameServer_ == null) {
          gameServer_ = new global::Axlebolt.Bolt.Protobuf.GameServer();
        }
        GameServer.MergeFrom(other.GameServer);
      }
      if (other.photonGame_ != null) {
        if (photonGame_ == null) {
          photonGame_ = new global::Axlebolt.Bolt.Protobuf.PhotonGame();
        }
        PhotonGame.MergeFrom(other.PhotonGame);
      }
      if (other.MaxSpectators != 0) {
        MaxSpectators = other.MaxSpectators;
      }
      spectators_.Add(other.spectators_);
      spectatorInvites_.Add(other.spectatorInvites_);
      if (other.NumberOfMembers != 0) {
        NumberOfMembers = other.NumberOfMembers;
      }
      if (other.NumberOfSpectators != 0) {
        NumberOfSpectators = other.NumberOfSpectators;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            OwnerPlayerId = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 32: {
            lobbyType_ = (global::Axlebolt.Bolt.Protobuf.LobbyType) input.ReadEnum();
            break;
          }
          case 40: {
            Joinable = input.ReadBool();
            break;
          }
          case 48: {
            MaxMembers = input.ReadInt32();
            break;
          }
          case 58: {
            data_.AddEntriesFrom(input, _map_data_codec);
            break;
          }
          case 66: {
            members_.AddEntriesFrom(input, _repeated_members_codec);
            break;
          }
          case 74: {
            invites_.AddEntriesFrom(input, _repeated_invites_codec);
            break;
          }
          case 82: {
            if (gameServer_ == null) {
              gameServer_ = new global::Axlebolt.Bolt.Protobuf.GameServer();
            }
            input.ReadMessage(gameServer_);
            break;
          }
          case 90: {
            if (photonGame_ == null) {
              photonGame_ = new global::Axlebolt.Bolt.Protobuf.PhotonGame();
            }
            input.ReadMessage(photonGame_);
            break;
          }
          case 96: {
            MaxSpectators = input.ReadInt32();
            break;
          }
          case 106: {
            spectators_.AddEntriesFrom(input, _repeated_spectators_codec);
            break;
          }
          case 114: {
            spectatorInvites_.AddEntriesFrom(input, _repeated_spectatorInvites_codec);
            break;
          }
          case 120: {
            NumberOfMembers = input.ReadInt32();
            break;
          }
          case 128: {
            NumberOfSpectators = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LobbyInvite : pb::IMessage<LobbyInvite> {
    private static readonly pb::MessageParser<LobbyInvite> _parser = new pb::MessageParser<LobbyInvite>(() => new LobbyInvite());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LobbyInvite> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LobbyInvite() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LobbyInvite(LobbyInvite other) : this() {
      lobbyId_ = other.lobbyId_;
      InviteCreator = other.inviteCreator_ != null ? other.InviteCreator.Clone() : null;
      date_ = other.date_;
      playerType_ = other.playerType_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LobbyInvite Clone() {
      return new LobbyInvite(this);
    }

    /// <summary>Field number for the "lobbyId" field.</summary>
    public const int LobbyIdFieldNumber = 1;
    private string lobbyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LobbyId {
      get { return lobbyId_; }
      set {
        lobbyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inviteCreator" field.</summary>
    public const int InviteCreatorFieldNumber = 2;
    private global::Axlebolt.Bolt.Protobuf.PlayerFriend inviteCreator_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Axlebolt.Bolt.Protobuf.PlayerFriend InviteCreator {
      get { return inviteCreator_; }
      set {
        inviteCreator_ = value;
      }
    }

    /// <summary>Field number for the "date" field.</summary>
    public const int DateFieldNumber = 3;
    private long date_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Date {
      get { return date_; }
      set {
        date_ = value;
      }
    }

    /// <summary>Field number for the "playerType" field.</summary>
    public const int PlayerTypeFieldNumber = 4;
    private global::Axlebolt.Bolt.Protobuf.LobbyPlayerType playerType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Axlebolt.Bolt.Protobuf.LobbyPlayerType PlayerType {
      get { return playerType_; }
      set {
        playerType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LobbyInvite);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LobbyInvite other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LobbyId != other.LobbyId) return false;
      if (!object.Equals(InviteCreator, other.InviteCreator)) return false;
      if (Date != other.Date) return false;
      if (PlayerType != other.PlayerType) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LobbyId.Length != 0) hash ^= LobbyId.GetHashCode();
      if (inviteCreator_ != null) hash ^= InviteCreator.GetHashCode();
      if (Date != 0L) hash ^= Date.GetHashCode();
      if (PlayerType != 0) hash ^= PlayerType.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LobbyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LobbyId);
      }
      if (inviteCreator_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(InviteCreator);
      }
      if (Date != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Date);
      }
      if (PlayerType != 0) {
        output.WriteRawTag(32);
        output.WriteEnum((int) PlayerType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LobbyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LobbyId);
      }
      if (inviteCreator_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InviteCreator);
      }
      if (Date != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Date);
      }
      if (PlayerType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PlayerType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LobbyInvite other) {
      if (other == null) {
        return;
      }
      if (other.LobbyId.Length != 0) {
        LobbyId = other.LobbyId;
      }
      if (other.inviteCreator_ != null) {
        if (inviteCreator_ == null) {
          inviteCreator_ = new global::Axlebolt.Bolt.Protobuf.PlayerFriend();
        }
        InviteCreator.MergeFrom(other.InviteCreator);
      }
      if (other.Date != 0L) {
        Date = other.Date;
      }
      if (other.PlayerType != 0) {
        PlayerType = other.PlayerType;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            LobbyId = input.ReadString();
            break;
          }
          case 18: {
            if (inviteCreator_ == null) {
              inviteCreator_ = new global::Axlebolt.Bolt.Protobuf.PlayerFriend();
            }
            input.ReadMessage(inviteCreator_);
            break;
          }
          case 24: {
            Date = input.ReadInt64();
            break;
          }
          case 32: {
            playerType_ = (global::Axlebolt.Bolt.Protobuf.LobbyPlayerType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class JoinLobbyRequest : pb::IMessage<JoinLobbyRequest> {
    private static readonly pb::MessageParser<JoinLobbyRequest> _parser = new pb::MessageParser<JoinLobbyRequest>(() => new JoinLobbyRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<JoinLobbyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinLobbyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinLobbyRequest(JoinLobbyRequest other) : this() {
      lobbyId_ = other.lobbyId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinLobbyRequest Clone() {
      return new JoinLobbyRequest(this);
    }

    /// <summary>Field number for the "lobbyId" field.</summary>
    public const int LobbyIdFieldNumber = 1;
    private string lobbyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LobbyId {
      get { return lobbyId_; }
      set {
        lobbyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as JoinLobbyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(JoinLobbyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LobbyId != other.LobbyId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LobbyId.Length != 0) hash ^= LobbyId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LobbyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LobbyId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LobbyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LobbyId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(JoinLobbyRequest other) {
      if (other == null) {
        return;
      }
      if (other.LobbyId.Length != 0) {
        LobbyId = other.LobbyId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            LobbyId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class JoinLobbyAsRequest : pb::IMessage<JoinLobbyAsRequest> {
    private static readonly pb::MessageParser<JoinLobbyAsRequest> _parser = new pb::MessageParser<JoinLobbyAsRequest>(() => new JoinLobbyAsRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<JoinLobbyAsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinLobbyAsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinLobbyAsRequest(JoinLobbyAsRequest other) : this() {
      lobbyId_ = other.lobbyId_;
      playerType_ = other.playerType_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinLobbyAsRequest Clone() {
      return new JoinLobbyAsRequest(this);
    }

    /// <summary>Field number for the "lobbyId" field.</summary>
    public const int LobbyIdFieldNumber = 1;
    private string lobbyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LobbyId {
      get { return lobbyId_; }
      set {
        lobbyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "playerType" field.</summary>
    public const int PlayerTypeFieldNumber = 2;
    private global::Axlebolt.Bolt.Protobuf.LobbyPlayerType playerType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Axlebolt.Bolt.Protobuf.LobbyPlayerType PlayerType {
      get { return playerType_; }
      set {
        playerType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as JoinLobbyAsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(JoinLobbyAsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LobbyId != other.LobbyId) return false;
      if (PlayerType != other.PlayerType) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LobbyId.Length != 0) hash ^= LobbyId.GetHashCode();
      if (PlayerType != 0) hash ^= PlayerType.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LobbyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LobbyId);
      }
      if (PlayerType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) PlayerType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LobbyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LobbyId);
      }
      if (PlayerType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PlayerType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(JoinLobbyAsRequest other) {
      if (other == null) {
        return;
      }
      if (other.LobbyId.Length != 0) {
        LobbyId = other.LobbyId;
      }
      if (other.PlayerType != 0) {
        PlayerType = other.PlayerType;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            LobbyId = input.ReadString();
            break;
          }
          case 16: {
            playerType_ = (global::Axlebolt.Bolt.Protobuf.LobbyPlayerType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class InvitePlayerToLobbyRequest : pb::IMessage<InvitePlayerToLobbyRequest> {
    private static readonly pb::MessageParser<InvitePlayerToLobbyRequest> _parser = new pb::MessageParser<InvitePlayerToLobbyRequest>(() => new InvitePlayerToLobbyRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InvitePlayerToLobbyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvitePlayerToLobbyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvitePlayerToLobbyRequest(InvitePlayerToLobbyRequest other) : this() {
      invitedPlayerId_ = other.invitedPlayerId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvitePlayerToLobbyRequest Clone() {
      return new InvitePlayerToLobbyRequest(this);
    }

    /// <summary>Field number for the "invitedPlayerId" field.</summary>
    public const int InvitedPlayerIdFieldNumber = 1;
    private string invitedPlayerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InvitedPlayerId {
      get { return invitedPlayerId_; }
      set {
        invitedPlayerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InvitePlayerToLobbyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InvitePlayerToLobbyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InvitedPlayerId != other.InvitedPlayerId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (InvitedPlayerId.Length != 0) hash ^= InvitedPlayerId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (InvitedPlayerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InvitedPlayerId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (InvitedPlayerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InvitedPlayerId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InvitePlayerToLobbyRequest other) {
      if (other == null) {
        return;
      }
      if (other.InvitedPlayerId.Length != 0) {
        InvitedPlayerId = other.InvitedPlayerId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            InvitedPlayerId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class InvitePlayerToLobbyAsRequest : pb::IMessage<InvitePlayerToLobbyAsRequest> {
    private static readonly pb::MessageParser<InvitePlayerToLobbyAsRequest> _parser = new pb::MessageParser<InvitePlayerToLobbyAsRequest>(() => new InvitePlayerToLobbyAsRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InvitePlayerToLobbyAsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvitePlayerToLobbyAsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvitePlayerToLobbyAsRequest(InvitePlayerToLobbyAsRequest other) : this() {
      invitedPlayerId_ = other.invitedPlayerId_;
      playerType_ = other.playerType_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InvitePlayerToLobbyAsRequest Clone() {
      return new InvitePlayerToLobbyAsRequest(this);
    }

    /// <summary>Field number for the "invitedPlayerId" field.</summary>
    public const int InvitedPlayerIdFieldNumber = 1;
    private string invitedPlayerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InvitedPlayerId {
      get { return invitedPlayerId_; }
      set {
        invitedPlayerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "playerType" field.</summary>
    public const int PlayerTypeFieldNumber = 2;
    private global::Axlebolt.Bolt.Protobuf.LobbyPlayerType playerType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Axlebolt.Bolt.Protobuf.LobbyPlayerType PlayerType {
      get { return playerType_; }
      set {
        playerType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InvitePlayerToLobbyAsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InvitePlayerToLobbyAsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InvitedPlayerId != other.InvitedPlayerId) return false;
      if (PlayerType != other.PlayerType) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (InvitedPlayerId.Length != 0) hash ^= InvitedPlayerId.GetHashCode();
      if (PlayerType != 0) hash ^= PlayerType.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (InvitedPlayerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InvitedPlayerId);
      }
      if (PlayerType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) PlayerType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (InvitedPlayerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InvitedPlayerId);
      }
      if (PlayerType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PlayerType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InvitePlayerToLobbyAsRequest other) {
      if (other == null) {
        return;
      }
      if (other.InvitedPlayerId.Length != 0) {
        InvitedPlayerId = other.InvitedPlayerId;
      }
      if (other.PlayerType != 0) {
        PlayerType = other.PlayerType;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            InvitedPlayerId = input.ReadString();
            break;
          }
          case 16: {
            playerType_ = (global::Axlebolt.Bolt.Protobuf.LobbyPlayerType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RevokePlayerInvitationToLobbyRequest : pb::IMessage<RevokePlayerInvitationToLobbyRequest> {
    private static readonly pb::MessageParser<RevokePlayerInvitationToLobbyRequest> _parser = new pb::MessageParser<RevokePlayerInvitationToLobbyRequest>(() => new RevokePlayerInvitationToLobbyRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RevokePlayerInvitationToLobbyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RevokePlayerInvitationToLobbyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RevokePlayerInvitationToLobbyRequest(RevokePlayerInvitationToLobbyRequest other) : this() {
      revokedPlayerId_ = other.revokedPlayerId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RevokePlayerInvitationToLobbyRequest Clone() {
      return new RevokePlayerInvitationToLobbyRequest(this);
    }

    /// <summary>Field number for the "revokedPlayerId" field.</summary>
    public const int RevokedPlayerIdFieldNumber = 1;
    private string revokedPlayerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RevokedPlayerId {
      get { return revokedPlayerId_; }
      set {
        revokedPlayerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RevokePlayerInvitationToLobbyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RevokePlayerInvitationToLobbyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RevokedPlayerId != other.RevokedPlayerId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RevokedPlayerId.Length != 0) hash ^= RevokedPlayerId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RevokedPlayerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RevokedPlayerId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RevokedPlayerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RevokedPlayerId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RevokePlayerInvitationToLobbyRequest other) {
      if (other == null) {
        return;
      }
      if (other.RevokedPlayerId.Length != 0) {
        RevokedPlayerId = other.RevokedPlayerId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            RevokedPlayerId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RefuseInvitationToLobbyRequest : pb::IMessage<RefuseInvitationToLobbyRequest> {
    private static readonly pb::MessageParser<RefuseInvitationToLobbyRequest> _parser = new pb::MessageParser<RefuseInvitationToLobbyRequest>(() => new RefuseInvitationToLobbyRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RefuseInvitationToLobbyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefuseInvitationToLobbyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefuseInvitationToLobbyRequest(RefuseInvitationToLobbyRequest other) : this() {
      lobbyId_ = other.lobbyId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefuseInvitationToLobbyRequest Clone() {
      return new RefuseInvitationToLobbyRequest(this);
    }

    /// <summary>Field number for the "lobbyId" field.</summary>
    public const int LobbyIdFieldNumber = 1;
    private string lobbyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LobbyId {
      get { return lobbyId_; }
      set {
        lobbyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RefuseInvitationToLobbyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RefuseInvitationToLobbyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LobbyId != other.LobbyId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LobbyId.Length != 0) hash ^= LobbyId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LobbyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LobbyId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LobbyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LobbyId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RefuseInvitationToLobbyRequest other) {
      if (other == null) {
        return;
      }
      if (other.LobbyId.Length != 0) {
        LobbyId = other.LobbyId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            LobbyId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class KickPlayerFromLobbyRequest : pb::IMessage<KickPlayerFromLobbyRequest> {
    private static readonly pb::MessageParser<KickPlayerFromLobbyRequest> _parser = new pb::MessageParser<KickPlayerFromLobbyRequest>(() => new KickPlayerFromLobbyRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<KickPlayerFromLobbyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KickPlayerFromLobbyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KickPlayerFromLobbyRequest(KickPlayerFromLobbyRequest other) : this() {
      kickedPlayerId_ = other.kickedPlayerId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KickPlayerFromLobbyRequest Clone() {
      return new KickPlayerFromLobbyRequest(this);
    }

    /// <summary>Field number for the "kickedPlayerId" field.</summary>
    public const int KickedPlayerIdFieldNumber = 1;
    private string kickedPlayerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string KickedPlayerId {
      get { return kickedPlayerId_; }
      set {
        kickedPlayerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as KickPlayerFromLobbyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(KickPlayerFromLobbyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (KickedPlayerId != other.KickedPlayerId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (KickedPlayerId.Length != 0) hash ^= KickedPlayerId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (KickedPlayerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(KickedPlayerId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (KickedPlayerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KickedPlayerId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(KickPlayerFromLobbyRequest other) {
      if (other == null) {
        return;
      }
      if (other.KickedPlayerId.Length != 0) {
        KickedPlayerId = other.KickedPlayerId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            KickedPlayerId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetInvitesToLobbyRequest : pb::IMessage<GetInvitesToLobbyRequest> {
    private static readonly pb::MessageParser<GetInvitesToLobbyRequest> _parser = new pb::MessageParser<GetInvitesToLobbyRequest>(() => new GetInvitesToLobbyRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetInvitesToLobbyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInvitesToLobbyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInvitesToLobbyRequest(GetInvitesToLobbyRequest other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInvitesToLobbyRequest Clone() {
      return new GetInvitesToLobbyRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetInvitesToLobbyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetInvitesToLobbyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetInvitesToLobbyRequest other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed partial class GetInvitesToLobbyResponse : pb::IMessage<GetInvitesToLobbyResponse> {
    private static readonly pb::MessageParser<GetInvitesToLobbyResponse> _parser = new pb::MessageParser<GetInvitesToLobbyResponse>(() => new GetInvitesToLobbyResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetInvitesToLobbyResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Axlebolt.Bolt.Protobuf.MatchmakingMessageReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInvitesToLobbyResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInvitesToLobbyResponse(GetInvitesToLobbyResponse other) : this() {
      lobbyInvites_ = other.lobbyInvites_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInvitesToLobbyResponse Clone() {
      return new GetInvitesToLobbyResponse(this);
    }

    /// <summary>Field number for the "lobbyInvites" field.</summary>
    public const int LobbyInvitesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Axlebolt.Bolt.Protobuf.LobbyInvite> _repeated_lobbyInvites_codec
        = pb::FieldCodec.ForMessage(10, global::Axlebolt.Bolt.Protobuf.LobbyInvite.Parser);
    private readonly pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.LobbyInvite> lobbyInvites_ = new pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.LobbyInvite>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Axlebolt.Bolt.Protobuf.LobbyInvite> LobbyInvites {
      get { return lobbyInvites_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetInvitesToLobbyResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetInvitesToLobbyResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!lobbyInvites_.Equals(other.lobbyInvites_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= lobbyInvites_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      lobbyInvites_.WriteTo(output, _repeated_lobbyInvites_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += lobbyInvites_.CalculateSize(_repeated_lobbyInvites_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetInvitesToLobbyResponse other) {
      if (other == null) {
        return;
      }
      lobbyInvites_.Add(other.lobbyInvites_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            lobbyInvites_.AddEntriesFrom(input, _repeated_lobbyInvites_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
